<a href="https://colab.research.google.com/github/PradeepChandrasekaran/PradeepResume/blob/main/Assignment%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
def fliplr(input):
  if(len(list(input.shape))>=2):
    list1=list(torch.split(input,1,1))
    list1.reverse()
    return torch.cat(list1,1)
  return "Input must be >=2 Dimension"

  
x = torch.arange(4).view(2, 2)
print(fliplr(x))
print(torch.fliplr(x))


x = torch.arange(18).view(2, 3,3)
print(fliplr(x))
print(torch.fliplr(x))


x=torch.arange(30).view(3,2,5)
print(fliplr(x))
print(torch.fliplr(x))


x = torch.arange(18).view(2, 3,3)
print(fliplr(x))
print(torch.fliplr(x))


print("Exception case")
x = torch.arange(4)
print(fliplr(x))

tensor([[1, 0],
        [3, 2]])
tensor([[1, 0],
        [3, 2]])
tensor([[[ 6,  7,  8],
         [ 3,  4,  5],
         [ 0,  1,  2]],

        [[15, 16, 17],
         [12, 13, 14],
         [ 9, 10, 11]]])
tensor([[[ 6,  7,  8],
         [ 3,  4,  5],
         [ 0,  1,  2]],

        [[15, 16, 17],
         [12, 13, 14],
         [ 9, 10, 11]]])
tensor([[[ 5,  6,  7,  8,  9],
         [ 0,  1,  2,  3,  4]],

        [[15, 16, 17, 18, 19],
         [10, 11, 12, 13, 14]],

        [[25, 26, 27, 28, 29],
         [20, 21, 22, 23, 24]]])
tensor([[[ 5,  6,  7,  8,  9],
         [ 0,  1,  2,  3,  4]],

        [[15, 16, 17, 18, 19],
         [10, 11, 12, 13, 14]],

        [[25, 26, 27, 28, 29],
         [20, 21, 22, 23, 24]]])
tensor([[[ 6,  7,  8],
         [ 3,  4,  5],
         [ 0,  1,  2]],

        [[15, 16, 17],
         [12, 13, 14],
         [ 9, 10, 11]]])
tensor([[[ 6,  7,  8],
         [ 3,  4,  5],
         [ 0,  1,  2]],

        [[15, 16, 17],
         [12, 13, 14],
       

In [4]:
def fmod(input,other,out=None):
  rem=torch.remainder(torch.abs(input), torch.abs(other))
  sign_tensor=torch.sign(input)
  return torch.mul(rem,sign_tensor)
input=torch.rand(3,4)
other=torch.tensor(5)
print(fmod(input,other))
print(torch.fmod(input,other))


input=torch.rand(3,4)
other=torch.rand(3,4)
print(fmod(input,other))
print(torch.fmod(input,other))


input=torch.tensor([1,-2,3,-4,5,6,-7,8]).to(torch.int32)
other=torch.tensor(2).to(torch.int32)
print(fmod(input,other))
print(torch.fmod(input,other))


input=torch.arange(51,69).to(torch.int32)
other=torch.arange(1,19).to(torch.int32)
print(fmod(input,other))
print(torch.fmod(input,other))

tensor([[0.0289, 0.1215, 0.5582, 0.5603],
        [0.9609, 0.3385, 0.3006, 0.5138],
        [0.0491, 0.0208, 0.0702, 0.4893]])
tensor([[0.0289, 0.1215, 0.5582, 0.5603],
        [0.9609, 0.3385, 0.3006, 0.5138],
        [0.0491, 0.0208, 0.0702, 0.4893]])
tensor([[0.4376, 0.1717, 0.0887, 0.2449],
        [0.0378, 0.2378, 0.2029, 0.7390],
        [0.3514, 0.1535, 0.0466, 0.1586]])
tensor([[0.4376, 0.1717, 0.0887, 0.2449],
        [0.0378, 0.2378, 0.2029, 0.7390],
        [0.3514, 0.1535, 0.0466, 0.1586]])
tensor([ 1,  0,  1,  0,  1,  0, -1,  0], dtype=torch.int32)
tensor([ 1,  0,  1,  0,  1,  0, -1,  0], dtype=torch.int32)
tensor([ 0,  0,  2,  2,  0,  2,  1,  2,  5,  0,  6,  2, 11,  8,  5,  2, 16, 14],
       dtype=torch.int32)
tensor([ 0,  0,  2,  2,  0,  2,  1,  2,  5,  0,  6,  2, 11,  8,  5,  2, 16, 14],
       dtype=torch.int32)


In [ ]:
def flip(input,dim):
  for i in dim:
    input=torch.split(input,1,i)
    list1=list(input)
    list1.reverse()
    input=torch.cat(list1,i)
  return input
t=torch.arange(8).view(2, 2, 2)
print("Original tensor")
print(t)
print("created flip op")
print(flip(t, [0,1]))
print("torch flip op")
print(torch.flip(t, [0,1]))


t=torch.arange(10).reshape(2,5)
print("Original tensor")
print(t)
print("created flip op")
print(flip(t, [0,1]))
print("torch flip op")
torch.flip(t, [0,1])

Original tensor
tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])
created flip op
tensor([[[6, 7],
         [4, 5]],

        [[2, 3],
         [0, 1]]])
torch flip op
tensor([[[6, 7],
         [4, 5]],

        [[2, 3],
         [0, 1]]])
Original tensor
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
created flip op
tensor([[9, 8, 7, 6, 5],
        [4, 3, 2, 1, 0]])
torch flip op


tensor([[9, 8, 7, 6, 5],
        [4, 3, 2, 1, 0]])

In [ ]:
def masked_select(input, mask, out=None):
   mask = mask.type(torch.float)
   input = torch.flatten(torch.mul(mask,input))
   out=torch.flatten(input[input.nonzero()])
   return out
x = torch.tensor([[ 0.3552, -2.3825, -0.8297,  0.3477],
        [-1.2035,  1.2252,  0.5002,  0.6248],
        [ 0.1307, -2.0608,  0.1244,  2.0139]])
print("Input Tensor")
print(x)
mask = x.ge(0.5)
print(mask)
print("created Masked_select op")
print(masked_select(x,mask))
print("torch Masked_select op")
print(torch.masked_select(x,mask))

Input Tensor
tensor([[ 0.3552, -2.3825, -0.8297,  0.3477],
        [-1.2035,  1.2252,  0.5002,  0.6248],
        [ 0.1307, -2.0608,  0.1244,  2.0139]])
tensor([[False, False, False, False],
        [False,  True,  True,  True],
        [False, False, False,  True]])
created Masked_select op
tensor([1.2252, 0.5002, 0.6248, 2.0139])
torch Masked_select op
tensor([1.2252, 0.5002, 0.6248, 2.0139])


In [ ]:
def split_cat_op(input_tensor,n,dim):
      tensor_split_tuple=torch.split(input_tensor,1,dim)
      return torch.cat((tensor_split_tuple[-n:]+tensor_split_tuple[:-n]),dim) 
def roll(input_tensor,shifts, dims=None):
      if(type(shifts)==int):
          return split_cat_op(input_tensor,shifts,dims)
      if(type(shifts)==tuple):
          for shift,dim in zip(shifts,dims):
            input_tensor=split_cat_op(input_tensor,shift,dim)
          return input_tensor;
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8]).view(4, 2)
print("created roll op")
print(roll(x, 1, 0))
print("Torch roll op")
print(torch.roll(x, 1, 0))

print("\n\n")

print("created roll op")
print(roll(x, -1, 0))
print("Torch roll op")
print(torch.roll(x, -1, 0))

print("\n\n")

print("created roll op")
print(roll(x, shifts=(2, 1), dims=(0, 1)))
print("Torch roll op")
print(torch.roll(x, shifts=(2, 1), dims=(0, 1)))

created roll op
tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])
Torch roll op
tensor([[7, 8],
        [1, 2],
        [3, 4],
        [5, 6]])



created roll op
tensor([[3, 4],
        [5, 6],
        [7, 8],
        [1, 2]])
Torch roll op
tensor([[3, 4],
        [5, 6],
        [7, 8],
        [1, 2]])



created roll op
tensor([[6, 5],
        [8, 7],
        [2, 1],
        [4, 3]])
Torch roll op
tensor([[6, 5],
        [8, 7],
        [2, 1],
        [4, 3]])


In [ ]:
def linspace(start,end,steps, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False):
  if(steps==1):
    steps=1
    end_v=end
  else:
    steps-=1
    end_v=end+1
  step_intervals=(end-start)/steps
  return torch.arange(start,end_v,step_intervals,out=out, dtype=dtype, layout=layout, device=device, requires_grad=requires_grad)
print("created linspace op")
print(linspace(3, 10, steps=5))
print("torch linspace op")
print(torch.linspace(3, 10, steps=5))


print("created linspace op")
print(linspace(-10, 10, 5))
print("torch linspace op")
print(torch.linspace(start=-10, end=10, steps=5))


print("created linspace op")
print(linspace(-10, 10, 1))
print("torch linspace op")
print(torch.linspace(start=-10, end=10, steps=1))

created linspace op
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
torch linspace op
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
created linspace op
tensor([-10.,  -5.,   0.,   5.,  10.])
torch linspace op
tensor([-10.,  -5.,   0.,   5.,  10.])
created linspace op
tensor([-10.])
torch linspace op
tensor([-10.])


In [ ]:
section=[1,2,1,2,2]
d=torch.randn(8,4)
print(d,d.shape)
print(torch.split(d,section,dim=0))

tensor([[ 0.7093, -0.4083, -0.2537,  0.9023],
        [-0.4761,  0.0159, -0.5090,  0.7895],
        [-1.2068,  0.7470,  0.1681, -0.6422],
        [ 0.5483, -0.6375, -1.2197, -0.4252],
        [-0.3197, -0.7282,  0.2903,  0.2676],
        [ 0.3557,  0.8117, -1.8224,  1.3717],
        [ 0.6680, -0.4570,  0.2947, -0.4524],
        [ 0.8225,  0.0490, -1.2372,  0.6156]]) torch.Size([8, 4])
(tensor([[ 0.7093, -0.4083, -0.2537,  0.9023]]), tensor([[-0.4761,  0.0159, -0.5090,  0.7895],
        [-1.2068,  0.7470,  0.1681, -0.6422]]), tensor([[ 0.5483, -0.6375, -1.2197, -0.4252]]), tensor([[-0.3197, -0.7282,  0.2903,  0.2676],
        [ 0.3557,  0.8117, -1.8224,  1.3717]]), tensor([[ 0.6680, -0.4570,  0.2947, -0.4524],
        [ 0.8225,  0.0490, -1.2372,  0.6156]]))


In [ ]:
#1.Reshaping a tensor
#refer:https://www.geeksforgeeks.org/reshaping-a-tensor-in-pytorch/
tensor_var=torch.arange(1,10);
print(tensor_var)
print(tensor_var.shape)
#a)reshape method ==>tensor_var.reshape(r,c)==>returns reshaped tensor
t1=tensor_var.reshape(3,3)
print(t1)
t2=tensor_var.reshape(9,1)
print(t2)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [ ]:
#flatten() method==>Nd Tensor to 1D tensor
tensor_var=torch.tensor([
            [1,2,3],
            [4,5,6],
            [7,8,9]
          ])
torch.flatten(tensor_var) #tensor_var.flatten()==>return vector
print(tensor_var)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
#c)tensor_var.view(r,c)
#refer:https://pytorch.org/docs/stable/generated/torch.Tensor.view.html,
#refer:https://stackoverflow.com/questions/50792316/what-does-1-mean-in-pytorch-view
#vector
tensor_var=torch.arange(16)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(4,4)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(-1,8)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(4,-1)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(-1)
print(tensor_var,tensor_var.size())



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]) torch.Size([16])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) torch.Size([4, 4])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]) torch.Size([2, 8])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) torch.Size([4, 4])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]) torch.Size([16])


In [ ]:
#tensor_var.resize_()
tensor_var=torch.arange(16)
print(tensor_var.resize_(1,2,8))

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]]])


In [ ]:
#squeeze==>reducing all its dimensions of inputs having size 1.
tensor_var=torch.tensor([[[[[0.],
[0.]]],


[[[0.],
[0.]]]]])
print(tensor_var.shape)
torch.squeeze(tensor_var),torch.squeeze(tensor_var).shape

torch.Size([1, 2, 1, 2, 1])


(tensor([[0., 0.],
         [0., 0.]]), torch.Size([2, 2]))

In [ ]:
#unsqueeze==>add dim at given position
tensor_var=torch.arange(5)
print(tensor_var,tensor_var.shape)
print(torch.unsqueeze(tensor_var,0))
print(torch.unsqueeze(tensor_var,1))

tensor([0, 1, 2, 3, 4]) torch.Size([5])
tensor([[0, 1, 2, 3, 4]])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [ ]:
#matrix multiplication 
#ref:https://www.geeksforgeeks.org/python-matrix-multiplication-using-pytorch/
#1)mm==>the matrix must be in same shape
mat1=torch.rand(3,4) 
mat2=torch.rand(4,3)
print(torch.mm(mat1,mat2),torch.mm(mat1,mat2).shape) 

tensor([[1.4680, 2.1072, 1.8932],
        [1.3905, 1.5624, 1.5121],
        [1.4995, 1.6706, 1.0445]]) torch.Size([3, 3])


In [ ]:
#matmaul
#matrix with 2 1d 
mat1=torch.tensor([1,2,3,4])
mat2=torch.tensor([5,6,7,8])
print(torch.matmul(mat1,mat2),torch.matmul(mat1,mat2).shape)
#matrix with 1d and 2d
mat1_1 = torch.tensor([3, 6, 2])
  
mat1_2 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]])
  
print(torch.matmul(mat1_1, mat1_2))

tensor(70) torch.Size([])
tensor([29, 38, 61])


In [ ]:
#expand()
#ref:https://www.tutorialspoint.com/how-to-perform-an-expand-operation-in-pytorch
tensor_var1=torch.tensor([[1],[2],[3]])
print(tensor_var1.shape)
tensor_var1=tensor_var.expand(3,4)
print(tensor_var1,tensor_var1.shape)

tensor_var1=torch.tensor([1,2,3])
tensor_var1=tensor_var1.expand(5,-1)
print(tensor_var1,tensor_var1.shape)

torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) torch.Size([5, 3])


In [ ]:
#narrow
tensor_var=torch.tensor([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(torch.narrow(tensor_var,0,0,3))
print(torch.narrow(tensor_var,0,1,2))

print(torch.narrow(tensor_var,1,0,2))
print(torch.narrow(tensor_var,1,1,2))



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [ ]:
#permute
tensor_var=torch.tensor([[1,2],[3,4],[5,6]])
print(tensor_var.shape)
tensor_var=torch.permute(tensor_var,(1,0))
print(tensor_var,tensor_var.shape)


torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]]) torch.Size([2, 3])


In [ ]:
import torch
#1)add(tensor1,tensor*,alpha==>multipler which multiplies with tensor2*)
t1=torch.tensor([1,2,3,4])
print(t1)
print(torch.add(t1,10))
print(torch.add(t1,10,alpha=10))
t2=torch.rand(4,1)
torch.add(t1,t2)

tensor([1, 2, 3, 4])
tensor([11, 12, 13, 14])
tensor([101, 102, 103, 104])


tensor([[1.6993, 2.6993, 3.6993, 4.6993],
        [1.1815, 2.1815, 3.1815, 4.1815],
        [1.2955, 2.2955, 3.2955, 4.2955],
        [1.0077, 2.0077, 3.0077, 4.0077]])

In [ ]:
#2)add_ ==> add with in place  
a = torch.tensor([[1,1],[1,1]])
b = torch.tensor(2)
c = torch.tensor(3)
a.add_(b,alpha=3)
print(a)

tensor([[7, 7],
        [7, 7]])


In [ ]:
#cat
t1=torch.tensor([[1,2],
              [3,4]])
t2=torch.tensor([[9,4],
              [8,5]])
print(t1)
t3=torch.cat((t1,t2),dim=0)
print(t3)
t3=torch.cat((t1,t2),dim=1)
print(t3)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4],
        [9, 4],
        [8, 5]])
tensor([[1, 2, 9, 4],
        [3, 4, 8, 5]])


STACK

In [ ]:
#1D TENSOR
t1=torch.rand(5)
t2=torch.rand(5)
torch.stack((t1,t2),dim=0),torch.stack((t1,t2),dim=1)

(tensor([[0.2402, 0.4902, 0.2986, 0.4896, 0.8011],
         [0.8402, 0.8239, 0.3081, 0.7673, 0.9500]]), tensor([[0.2402, 0.8402],
         [0.4902, 0.8239],
         [0.2986, 0.3081],
         [0.4896, 0.7673],
         [0.8011, 0.9500]]))

In [ ]:
#2d tensor for stack
t1=torch.tensor([[1,2,7],
              [3,4,8]])
t2=torch.tensor([[9,4,9],
              [8,5,1]])
print(torch.stack((t1,t2),dim=0),"\n",torch.stack((t1,t2),dim=1),"\n",torch.stack((t1,t2),dim=2))

tensor([[[1, 2, 7],
         [3, 4, 8]],

        [[9, 4, 9],
         [8, 5, 1]]]) 
 tensor([[[1, 2, 7],
         [9, 4, 9]],

        [[3, 4, 8],
         [8, 5, 1]]]) 
 tensor([[[1, 9],
         [2, 4],
         [7, 9]],

        [[3, 8],
         [4, 5],
         [8, 1]]])


In [ ]:
import torch as t
t1=t.tensor([[1,2],[3,4]],dtype=t.float64)
print(t1)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
t1=t1.new_full((2,2),1)
t2=t.rand((2,2),requires_grad=True)
c=t1.add_(t2).sum()
c.backward()
t2.grad,c.grad

/usr/local/lib/python3.7/dist-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad


(tensor([[1., 1.],
         [1., 1.]]), None)

In [ ]:
x=t.rand(3,2)
print(x)
t1=t.view_as_complex(x)
t.is_complex(t1)


tensor([[0.4662, 0.5603],
        [0.7589, 0.7052],
        [0.7738, 0.1385]])


True

In [ ]:
t.randn(2, 2).stride()

(2, 1)

In [ ]:
import torch
a = torch.arange(5)
b = torch.arange(10).reshape(5, 2)
print(a,b)
torch.column_stack((a, b, b))

tensor([0, 1, 2, 3, 4]) tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


tensor([[0, 0, 1, 0, 1],
        [1, 2, 3, 2, 3],
        [2, 4, 5, 4, 5],
        [3, 6, 7, 6, 7],
        [4, 8, 9, 8, 9]])

In [ ]:
x = torch.arange(3).view(1, 3)
y = torch.arange(2).view(2, 1)
print(x,y)
a, b = torch.broadcast_tensors(x, y)
a.size()
a

tensor([[0, 1, 2]]) tensor([[0],
        [1]])


tensor([[0, 1, 2],
        [0, 1, 2]])

In [ ]:
sorted_sequence = torch.tensor([[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]])
sorted_sequence
values = torch.tensor([[3, 6, 9], [3, 6, 9]])
values
torch.searchsorted(sorted_sequence, values)


tensor([[1, 3, 4],
        [1, 2, 4]])