<a href="https://colab.research.google.com/github/PradeepChandrasekaran/PradeepResume/blob/main/Tensor_operation_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [24]:
#1.Reshaping a tensor
#refer:https://www.geeksforgeeks.org/reshaping-a-tensor-in-pytorch/
tensor_var=torch.arange(1,10);
print(tensor_var)
print(tensor_var.shape)
#a)reshape method ==>tensor_var.reshape(r,c)==>returns reshaped tensor
t1=tensor_var.reshape(3,3)
print(t1)
t2=tensor_var.reshape(9,1)
print(t2)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [21]:
#flatten() method==>Nd Tensor to 1D tensor
tensor_var=torch.tensor([
            [1,2,3],
            [4,5,6],
            [7,8,9]
          ])
torch.flatten(tensor_var) #tensor_var.flatten()==>return vector
print(tensor_var)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [30]:
#c)tensor_var.view(r,c)
#refer:https://pytorch.org/docs/stable/generated/torch.Tensor.view.html,
#refer:https://stackoverflow.com/questions/50792316/what-does-1-mean-in-pytorch-view
#vector
tensor_var=torch.arange(16)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(4,4)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(-1,8)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(4,-1)
print(tensor_var,tensor_var.size())

tensor_var=tensor_var.view(-1)
print(tensor_var,tensor_var.size())



tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]) torch.Size([16])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) torch.Size([4, 4])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]) torch.Size([2, 8])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]) torch.Size([4, 4])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]) torch.Size([16])


In [32]:
#tensor_var.resize_()
tensor_var=torch.arange(16)
print(tensor_var.resize_(1,2,8))

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]]])


In [39]:
#squeeze==>reducing all its dimensions of inputs having size 1.
tensor_var=torch.tensor([[[[[0.],
[0.]]],


[[[0.],
[0.]]]]])
print(tensor_var.shape)
torch.squeeze(tensor_var),torch.squeeze(tensor_var).shape

torch.Size([1, 2, 1, 2, 1])


(tensor([[0., 0.],
         [0., 0.]]), torch.Size([2, 2]))

In [40]:
#unsqueeze==>add dim at given position
tensor_var=torch.arange(5)
print(tensor_var,tensor_var.shape)
print(torch.unsqueeze(tensor_var,0))
print(torch.unsqueeze(tensor_var,1))

tensor([0, 1, 2, 3, 4]) torch.Size([5])
tensor([[0, 1, 2, 3, 4]])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])


In [42]:
#matrix multiplication 
#ref:https://www.geeksforgeeks.org/python-matrix-multiplication-using-pytorch/
#1)mm==>the matrix must be in same shape
mat1=torch.rand(3,4) 
mat2=torch.rand(4,3)
print(torch.mm(mat1,mat2),torch.mm(mat1,mat2).shape) 

tensor([[1.4680, 2.1072, 1.8932],
        [1.3905, 1.5624, 1.5121],
        [1.4995, 1.6706, 1.0445]]) torch.Size([3, 3])


In [50]:
#matmaul
#matrix with 2 1d 
mat1=torch.tensor([1,2,3,4])
mat2=torch.tensor([5,6,7,8])
print(torch.matmul(mat1,mat2),torch.matmul(mat1,mat2).shape)
#matrix with 1d and 2d
mat1_1 = torch.tensor([3, 6, 2])
  
mat1_2 = torch.tensor([[1, 2, 3],
                       [4, 3, 8],
                       [1, 7, 2]])
  
print(torch.matmul(mat1_1, mat1_2))

tensor(70) torch.Size([])
tensor([29, 38, 61])


In [58]:
#expand()
#ref:https://www.tutorialspoint.com/how-to-perform-an-expand-operation-in-pytorch
tensor_var1=torch.tensor([[1],[2],[3]])
print(tensor_var1.shape)
tensor_var1=tensor_var.expand(3,4)
print(tensor_var1,tensor_var1.shape)

tensor_var1=torch.tensor([1,2,3])
tensor_var1=tensor_var1.expand(5,-1)
print(tensor_var1,tensor_var1.shape)

torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]) torch.Size([3, 4])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) torch.Size([5, 3])


In [72]:
#narrow
tensor_var=torch.tensor([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(torch.narrow(tensor_var,0,0,3))
print(torch.narrow(tensor_var,0,1,2))

print(torch.narrow(tensor_var,1,0,2))
print(torch.narrow(tensor_var,1,1,2))



tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])


In [77]:
#permute
tensor_var=torch.tensor([[1,2],[3,4],[5,6]])
print(tensor_var.shape)
tensor_var=torch.permute(tensor_var,(1,0))
print(tensor_var,tensor_var.shape)


torch.Size([3, 2])
tensor([[1, 3, 5],
        [2, 4, 6]]) torch.Size([2, 3])
